# Generated by Django 3.0.8 on 2020-09-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
