# Generated by Django 3.0.8 on 2021-01-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupware', '0004_auto_20200921_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='cover_photo_url',
        ),
        migrations.AddField(
            model_name='activity',
            name='cover_photo',
            field=models.ImageField(default='media/default.png', upload_to='media/'),
        ),
    ]
