# Generated by Django 3.0.8 on 2020-08-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=5)),
                ('student_id', models.CharField(max_length=8)),
                ('email', models.CharField(default='', max_length=30)),
                ('phone_number', models.CharField(max_length=11)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
    ]
