# Generated by Django 3.0.8 on 2020-09-03 06:55

from django.db import migrations, models
import django.db.models.deletion
import groupware.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('information', models.TextField()),
                ('semester', models.IntegerField(choices=[(1, 'FIRST'), (2, 'SECOND')], default=groupware.models.Semester['FIRST'])),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Recruitment')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('student_id', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=11)),
                ('passed', models.BooleanField(default=False)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Recruitment')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('applicant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruit.Applicant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Question')),
            ],
        ),
    ]
