# Generated by Django 3.0.8 on 2020-08-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recruit',
            new_name='GroupMember',
        ),
    ]
