# Generated by Django 3.0.8 on 2021-02-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
