# Generated by Django 3.0.8 on 2020-10-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200828_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_regular_member',
            field=models.BooleanField(default=False),
        ),
    ]
