# Generated by Django 3.0.8 on 2020-08-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200827_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email_verified',
        ),
    ]
