# Generated by Django 3.0.8 on 2020-08-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
