# Generated by Django 3.0.8 on 2020-08-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupware', '0002_accountbook'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='activities',
        ),
    ]
