# Generated by Django 3.0.8 on 2020-08-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupware', '0002_auto_20200814_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
