# Generated by Django 3.0.8 on 2020-08-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupware', '0004_auto_20200814_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
